### ISSUE TITLE
Can't install via NPM + UMD wrapper is broken

### ISSUE THREAD

**Issue by jeffijoe** [blittle/backbone-nested-models#22]
`backbone-nested` on NPM is not this library, despite the package.json saying so.

I managed to pull down this module using Napa, but it appears the UMD wrapper is broken.

I am using webpack (common.js). :)

**Comment by blittle** [comment]
I'll try to fix this today or tomorrow, but if you'd like, do a pull req and I'll merge.

**Comment by jeffijoe** [comment]
I'll have a stab at it, but the NPM thing is something you'd have to fix since you run the master. :)

**Comment by jeffijoe** [comment]
Can't get the tests running, I don't think I'm of much help. Haven't used Karma before either.

**Comment by jeffijoe** [comment]
@blittle  Any news? This library is amazing in it's simplicity and it *Just Works™*, would be a shame if it went inactive.

Really, nested models and collections gets almost too easy with this library. :)

**Comment by blittle** [comment]
Sorry for the delay, I'll have a fix later today.

**Comment by blittle** [comment]
https://www.npmjs.com/package/backbone-nested-models

**Comment by jeffijoe** [comment]
Sweet! Thanks!
