### ISSUE TITLE
get of relation doesn't work in initialize function

### ISSUE THREAD

**Issue by perekrestov-igor** [blittle/backbone-nested-models#28]
var someModel = Backbone.Model.extend({
__defaults: {
____attr1: "comment",
____attr2: false
__},
__relations: {
____someRelation: Backbone.Collection
__},
__initialize: function() {
____this.get("attr1") // work well
____this.get("someRelation") // returm undefined
__}
});

**Comment by biperch** [comment]
you need set someRelation of defaults

__defaults: {
____attr1: "comment",
____attr2: false,
____someRelation : null
__},

**Comment by perekrestov-igor** [comment]
thanks, 
but why so slowly?

**Comment by biperch** [comment]
Unfortunately, yesterday took an extension, and I ran into this problem. I decided to answer suddenly someone come in handy)

**Comment by perekrestov-igor** [comment]
Sorry, my comment are incorrected, I had thought that you are author this library

Thanks  for help
