### ISSUE TITLE
A model relation with default value is set wrongly

### ISSUE THREAD

**Issue by royling** [blittle/backbone-nested-models#30]
see the below example:
```js
var Author = Backbone.Model.extend({
  defaults: {
    name: 'test',
    age: 20
  }
});
var Book = Backbone.Model.extend({
  relations: {
    author: Author
  },
  defaults: {
    author: new Author()
  }
});

var book = new Book({name: 'go!'});
```
`book.toJSON().author` is a Backbone.Model **like** instance (because `instanceof Backbone.Model` returns false), instead of the JSON of the defaults of Author.
it seems that `book.attributes.author = new Author(new Author)`

**Comment by royling** [comment]
In this case, the `relation` from https://github.com/blittle/backbone-nested-models/blob/master/backbone-nested-models.js#L30 is `undefined`, and it will take the default value as the source to instantiate the attribute. That results to the wrong value.

**Comment by royling** [comment]
PR submitted, pls review and merge if ok. Close this issue.

**Comment by royling** [comment]
I've to reopen the issue, because the fix does not work properly when working with events.

With the above fix, the single instance in the `defaults` may be **shared** in a collection of this model, that will cause the below event binding issue:

```js
var Books = Backbone.Collection.extend({
  initialize: function() {
    this.model.get('author').on('change', ...); // the author instance may be just the single default one
    // all books in the collection are listening to change event on **one** instance,
    // but in fact we may expect each book to just listen to its own author change
  }
});
```

I will send out another PR to fix this issue and also the collection case.

**Comment by royling** [comment]
PR#32 submitted to fix the new issue.

**Comment by blittle** [comment]
Thx for the pr!
